config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true

  after_commit { BroadcastMessageJob.perform_later self }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        flash[:success] = 'Room was successfully created.'
        format.html { redirect_to @room }
        format.json { render :show, status: :created, location: @room }
      else
        flash[:danger] = 'Error in creating Room.'
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller_full_name
    params[:controller].present? ? params[:controller].gsub('/', '_') : controller_name
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name.to_s %>" role="alert">
    <%= msg.to_s %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "OSC", root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to root_path, class: 'nav-link' do %>
          Home<span class="sr-only">(current)</span>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to 'New Room', new_room_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'My Rooms', '#', class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Edit Account', edit_user_registration_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link' %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oldschool Chatroom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <%= render 'layouts/flashes' %>

    <div class="container <%= controller_full_name %> <%= action_name %>"><%= yield %></div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :room_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h1>Bootstrap 4 Learning</h1>
  <div>
<div>

<div class="row">
  <% @rooms.each do |room| %>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= room.name %></h4>
          <h6 class="card-subtitle"></h6>
          <p class="card-text"><%= room.description %></p>
          <%= link_to room do %>
            <button type="button" class="btn btn-primary">Join</button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="row"><!-- title of room -->
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h2><%= @room.name %></h2>
    <p><%= @room.description %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10"><!-- submitted messages -->
    <div id="messages_window" class="border">
      Column of live messages
    </div>
    <div class="form-group">
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>

  <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2"><!-- users in room -->
    Column of chatters online
  </div>
</div>